version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: sso-container-db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: sso
      MYSQL_USER: user
      MYSQL_PASSWORD: pass1234567
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql